# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-pytorch-model-service
spec:
  selector:
    app: K8S
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
