channels:
- conda-forge
dependencies:
- python=3.7.13
- pip<=22.1.2
- pip:
  - mlflow
  - astunparse==1.6.3
  - cloudpickle==2.2.0
  - ipython==7.34.0
  - numpy==1.19.5
  - torch==1.9.0
  - tqdm==4.59.0
name: mlflow-env
